Fix dark mode
saleor/saleor-app-payment-adyen pull request #118
Opened 2023-04-12 15:37 UTC by witoszekdev

Fixed #48

2023-04-13 15:29 UTC, mmiszy requested changes

2023-04-13 15:29 UTC, mmiszy commented on src/modules/ui/Input/Input.tsx
> +            })}
Is there a reason we're not using `Input` from the macaw-ui and instead replicating the design here on our own?

2023-04-13 15:30 UTC, witoszekdev commented on src/modules/ui/Input/Input.tsx
> +            })}
Replacing existing input would completely break our layout right now (e.g. Select) so until we replace everything to use macaw I would leave it

2023-04-14 12:58 UTC, mmiszy approved these changes

2023-04-14 13:02 UTC, merged