Add tests for webhook service
saleor/saleor-app-payment-adyen pull request #306
Opened 2023-05-30 08:37 UTC by witoszekdev

2023-05-30 20:17 UTC, mmiszy approved these changes

2023-05-30 20:17 UTC, mmiszy requested changes
Run `pnpm changeset` and follow the wizard.

2023-05-31 10:08 UTC, witoszekdev commented on src/__tests__/test-env.mjs
>    TEST_ADYEN_API_KEY_ID: process.env.TEST_ADYEN_API_KEY_ID,
Done https://github.com/saleor/saleor-docs/pull/786

2023-06-01 11:25 UTC, mmiszy approved these changes

2023-06-01 11:29 UTC, merged