Add configuration for Client Key allowed origins
saleor/saleor-app-payment-adyen pull request #57
Opened 2023-04-03 13:14 UTC by witoszekdev

Fixes #29

- [x] add react-query debugger
- [x] remove usage of useQueryClient, use trpc.useContext
- [x] Refactor setting api key: preselect client key and merchant when scope is merchant
- [x] Fix error when returning undefined query data (getAllowedOrigins)
- [x] Optimistic updates for delete app config
- [x] add default onError handler
- [x] remove useless onError handlers in useQuery and useMutation (prefer default)
- [x] Handle root error in forms

2023-04-07 13:24 UTC, mmiszy requested changes

2023-04-07 13:24 UTC, mmiszy commented on src/modules/adyen-configuration/adyen-configuration.test.ts
> +            key: "adyen-config-public__https://saleor.localhost:8080/graphql/",
```suggestion
            key: `adyen-config-public__${testEnv.TEST_SALEOR_API_URL}`,
```

2023-04-07 13:24 UTC, mmiszy commented on src/modules/adyen-configuration/adyen-key-utils.ts
> +  }
```suggestion
  const [myKeyError, myKey] = await unpackPromise(adyenManagement.MyAPICredentialApi.getApiCredentialDetails());
  if (myKeyError) {
    throw new InvalidPrivateKeyError("Invalid private API key");
  }
```

2023-04-07 13:24 UTC, mmiszy commented on src/modules/adyen-configuration/adyen-key-utils.ts
> +    logger.info({ companyScopeKey }, "Got company scoped key");
Is `companyScopeKey` public? If not, we should change the logger level to `debug`
```suggestion
    logger.debug({ companyScopeKey }, "Got company scoped key");
```

2023-04-07 13:24 UTC, mmiszy commented on src/modules/adyen-configuration/adyen-key-utils.ts
> +  } catch (_) {
Shouldn't we add some conditions here? What if the request failed for a different reason than the fact `keyId` was not a company key?

2023-04-07 13:24 UTC, mmiszy commented on src/modules/adyen-configuration/adyen-key-utils.ts
> +}
Ditto

2023-04-07 13:24 UTC, mmiszy commented on src/modules/adyen-resources/adyen-resources-config.ts
> +    .url("This isn't a valid URL. Remember that it must start with http:// or https://"),
Maybe we shouldn't suggest using http:// here and only keep https?

2023-04-07 13:24 UTC, mmiszy commented on src/modules/adyen-resources/adyen-resources.router.test.ts
> +      if (testEnv.POLLY_MODE === "record" || testEnv.POLLY_MODE === "record_missing") {
```suggestion
    it("deletes origin from the list of allowed origins for the client key in Adyen", async (t) => {
      const ctx = createFakeTrpcContext();
      const caller = appRouter.createCaller(ctx);

      const createInput: inferProcedureInput<AppRouter["adyenResources"]["addAllowedOrigin"]> = {
        domain: "http://delete-example.com",
      };

      await caller.adyenResources.addAllowedOrigin(createInput);

      const allowedOrigins = await caller.adyenResources.getAllowedOrigins();

      const createdOrigin = allowedOrigins.find(
        (origin) => origin.domain === "http://delete-example.com",
      );
      expect(createdOrigin).toBeDefined();
      expect(createdOrigin?.id).toBeDefined();

      invariant(createdOrigin?.id);

      const deleteInput: inferProcedureInput<AppRouter["adyenResources"]["deleteAllowedOrigin"]> = {
        originId: createdOrigin?.id,
      };

      await caller.adyenResources.deleteAllowedOrigin(deleteInput);

      if (t.polly?.mode === 'record') {
```

2023-04-07 13:24 UTC, mmiszy commented on src/modules/ui/ConfigureOrigins/ConfigureOrigins.tsx
> +          </ul>
If there's do `data`, there shouldn't be `<ul>` either. Just `<Text>`

2023-04-07 13:24 UTC, mmiszy commented on src/modules/ui/ConfigureOrigins/ConfigureOrigins.tsx
> +                .filter((origin) => origin.id)
Is it possible after filtering there will be no more items in the list?

2023-04-07 13:24 UTC, mmiszy commented on src/modules/ui/ConfigureOrigins/OriginListItem.tsx
> +  const { isLoading: isRemoving, mutate: deleteOrigin } =
```suggestion
  const { isLoading: isDeleting, mutate: deleteOrigin } =
```

2023-04-07 13:24 UTC, mmiszy commented on src/modules/ui/WebhooksConfigurator/WebhooksConfigurator.tsx
> +    await context.adyenResources.getWebhooks.invalidate();
Is there a reason we're awaiting the 2nd one but not the 1st?

2023-04-07 13:39 UTC, witoszekdev commented on src/modules/adyen-resources/adyen-resources-config.ts
> +    .url("This isn't a valid URL. Remember that it must start with http:// or https://"),
Well, you **can** add `http://` in Adyen ;)
I added that because if you test locally, you'll need to provide `http://localhost:...`

2023-04-07 13:44 UTC, witoszekdev commented on src/modules/ui/ConfigureOrigins/ConfigureOrigins.tsx
> +                .filter((origin) => origin.id)
Yes, theoretically Adyen can return list of origins without `id`'s (it's marked as nullable in their SDK) which we can do nothing with really (maybe we could display them but without delete button? 🤔)

2023-04-11 09:02 UTC, witoszekdev commented on src/modules/ui/WebhooksConfigurator/WebhooksConfigurator.tsx
> +    await context.adyenResources.getWebhooks.invalidate();
nope, changed that

2023-04-11 09:53 UTC, mmiszy submitted a review, later dismissed

2023-04-11 10:32 UTC, mmiszy approved these changes

2023-04-11 10:32 UTC, merged